### PR TITLE
Use light colour scheme for widget

### PR DESCRIPTION
**Pull request by segan5**
- use light colour scheme for widget
- also expanded the selection of white values in the widget to be inline with wheel in the official LIFX iOS app

### CODE REVIEW

**Comment by tatey** [comment]
Hello again @segan5 😄. Thanks for updating the widget plist.

> use light colour scheme for widget

Great

> also expanded the selection of white values in the widget to be inline with wheel in the official LIFX iOS app

Lovely!

I'm happy to merge this PR as is, but was wondering if you would have a crack at fixing the alignment of the cells first? If not, then I'll split it out into a new issue.

**Comment by tatey** [comment]
Also do you know what happens with older versions of macOS if we specify this attribute in the plist? I'm guessing it just gets ignored.

**Comment by segan5** [comment]
Hi! Haven't had a chance to look at alignment but that may take a bit longer to fix. Maybe split out into another issue?

Behaviour with that info.plist entry on older versions of macOS is to show the dark look. Basically it's ignored as you said.

**Comment by tatey** [comment]
> Hi! Haven't had a chance to look at alignment but that may take a bit longer to fix. Maybe split out into another issue?

Done. See https://github.com/tatey/Lighting/issues/24

> Behaviour with that info.plist entry on older versions of macOS is to show the dark look. Basically it's ignored as you said.

Good to know.

I've merged and updated the CHANGELOG in https://github.com/tatey/Lighting/commit/0003b688b84eb0e568e8d09a5e6f0d4f0ca0faca. I don't want to cut a new release until I can take screenshots of it working nicely on 10.12.

**Pull request merged**
