### PR TITLE
Add context menus to set color/brightness

### PR DESCRIPTION
**Pull request by lparry**
I hacked for a bit to get some right-click menus to set a few basic whites, a few brightnesses and some colours and came up with this.

I dont actually really know anything about Swift or OS X programming so I'm sure this probably needs some cleaning up to fit with idioms of the platform, but it seems to work as it is.

### CODE REVIEW

**Comment by bradfeehan** [comment]
Not affiliated with this project, but I was waiting for this, thanks! :heart_eyes:

**Comment by lparry** [comment]
As a follow up, this works perfectly in the simulator, but for the built .app the widget seems to fail to find any lights. NFI if it's me not knowing how to build a final product in xcode or if there's something else wrong, but I'd love any pointers

**Comment by lparry** [comment]
scratch most of that last comment. figured out xcodebuild on the command line gives me a good executable, but it seems like the "Today Widget" section in Yosemite has some bugs around replacing widgets with newer versions. I ended up nuking every copy of "Lighting.Widget" I could find on my hdd, and having to reboot before the old one would go away and I could install the updated one

**Comment by tatey** [comment]
Thanks @lparry!

This is a great addition to the project. I'll merge and tidy up in master.

**Comment by tatey** [comment]
New release: https://github.com/tatey/Lighting/releases/tag/1.1.0

**Pull request merged**
